#!/bin/bash
git config --global  user.name "popoASM"
git config --global  user.email "pratyayaborborah@gmail.com"

#

# Fix TimeZone
sudo ln -snf /usr/share/zoneinfo/Asia/Kolkata /etc/localtime

#tg
tg(){
	bot_api=$bot_token
	your_telegram_id=$1 
	msg=$2 
	curl -s "https://api.telegram.org/bot${bot_token}/sendmessage" --data "text=$msg&chat_id=${your_telegram_id}&parse_mode=html"
}

id=620358472 
tg $id "✴️ holland1 ROM compile status: triggered!.
https://cirrus-ci.com/task/$CIRRUS_TASK_ID ✴️"

mkdir -p /tmp/rom 
cd /tmp/rom

repo init -q --no-repo-verify --depth=1 -u git://github.com/LineageOS/android.git -b lineage-17.1 -g default,-device,-mips,-darwin,-notdefault
git clone https://github.com/popoASM/local_manifest.git --depth=1 -b main .repo/local_manifests
repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j 30 || repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j 8


# Normal build steps
source build/envsetup.sh
lunch lineage_E-userdebug
export CCACHE_DIR=/tmp/ccache
export CCACHE_EXEC=$(which ccache)
export USE_CCACHE=1
ccache -M 20G 
ccache -o compression=true 
ccache -z

#tg
tg(){
	bot_api=$bot_token
	your_telegram_id=$1 
	msg=$2
	curl -s "https://api.telegram.org/bot${bot_token}/sendmessage" --data "text=$msg&chat_id=${your_telegram_id}&parse_mode=html"
}
id=620358472
tg $id "✳️holland1 compile status: started✳️"

#make api-stubs-docs || echo no problem
#make system-api-stubs-docs || echo no problem
#make test-api-stubs-docs || echo no problem
make bacon -j8

#uploads
#up(){
#	curl --upload-file $1 https://transfer.sh/$(basename $1); echo
#	# 14 days, 10 GB limit
#}

time rclone copy /tmp/rom/out/target/product/holland1/dotOS*zip brrbrr:rom -P
tg $id "✅holland1 compile status: finished✅"

ccache -s

cd /tmp

com () 
{ 
    tar --use-compress-program="pigz -k -$2 " -cf $1.tar.gz $1
}

time com ccache 1

tg $id "holland1 ROM compile status:
ccache uploading started at:- $(date)."

time rclone copy ccache.tar.gz brrbrr:ccache -P 

tg $id "✅holland1 ccache uploaded successfully✅"
