#!/bin/bash
df -h
free -h
nproc

mkdir -p ~/.config/rclone
echo "$rc_conf" > ~/.config/rclone/rclone.conf

cd /tmp 
time rclone copy brrbrr:/ccache/ccache.tar.gz /tmp
time tar xf ccache.tar.gz  
rm -rf ccache.tar.gz
